routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('addresses', 'AddressesController');
    Route::resource('establishments', 'EstablishmentsController');
    Route::prefix('establishments/addresses/{address}')->group(function () {
        Route::resource('evaluations', 'EvaluationsController');
    });
    Route::get('/user/evaluations', 'UsersController@evaluations')->name('users.evaluations');
});

app/Establishment.php
<?php
/**
 * Establishment File
 *
 * PHP version 7
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Establishment Class
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */
class Establishment extends Model
{
    protected $fillable = [
        'name',
        'type_id',
    ];

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function addresses()
    {
        return $this->hasMany(Address::class);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function type()
    {
        return $this->belongsTo(EstablishmentType::class);
    }

    /**
     * Save address information
     *
     * @param Address $address the address
     *
     * @return void
     */
    public function saveAddress(Address $address)
    {
        if (!$address->exists && !$this->addresses->contains($address)) {
            $this->addresses()->save($address);
        }
    }
}

app/EstablishmentType.php
<?php
/**
 * EstablishmentType File
 *
 * PHP version 7
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * EstablishmentType Class
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */
class EstablishmentType extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/EstablishmentsController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Establishment;
use App\EstablishmentType;
use App\Http\Requests\CreateEstablishmentRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EstablishmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('establishments.create', ['types' => EstablishmentType::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEstablishmentRequest $request)
    {
        $address = Address::firstOrNew($request->only((new Address())->getFillable()));

        $establishment = Establishment::firstOrCreate($request->only((new Establishment())->getFillable()));
        $establishment->saveAddress($address);

        return redirect()->route('evaluations.create', $address);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Establishment  $establishment
     * @return \Illuminate\Http\Response
     */
    public function show(Establishment $establishment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Establishment  $establishment
     * @return \Illuminate\Http\Response
     */
    public function edit(Establishment $establishment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Establishment  $establishment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Establishment $establishment)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Establishment  $establishment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Establishment $establishment)
    {
        //
    }
}

resources/views/establishments/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Novo Estabelecimento</div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('establishments.store') }}">
                            {{ csrf_field() }}
                            <fieldset>
                                <legend>Estabelecimento:</legend>
                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label for="name" class="col-md-1 control-label">Nome:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}">

                                        @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('type_id') ? ' has-error' : '' }}">
                                    <label class="col-md-1 control-label">Tipo</label>
                                    <div class="col-md-4">
                                        <select class="form-control " name="type_id" id="type">
                                            @foreach($types as $type)
                                                <option value="{{ $type->id }}" {{ (collect(old('type_id'))->contains($type->id)) ? 'selected':'' }}>{{ $type->name }}</option>
                                            @endforeach
                                        </select>

                                        @if ($errors->has('type'))
                                            <span class="help-block">
                                                    <strong>{{ $errors->first('type') }}</strong>
                                                </span>
                                        @endif
                                    </div>
                                </div>
                            </fieldset>

                            <fieldset>
                                <legend>Endereço</legend>
                                <div class="form-group{{ $errors->has('street') ? ' has-error' : '' }}">
                                    <label for="name" class="col-md-1 control-label">Rua:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="street" value="{{ old('street') }}">

                                        @if ($errors->has('street'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('street') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <label for="name" class="col-md-2 control-label">Número:</label>
                                    <div class="col-md-2">
                                        <input id="name" type="text" class="form-control" name="number" value="{{ old('number') }}">

                                        @if ($errors->has('number'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('number') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('district') ? ' has-error' : '' }}">
                                    <label for="name" class="col-md-1 control-label">Bairro:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="district" value="{{ old('district') }}">

                                        @if ($errors->has('district'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('district') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <label for="name" class="col-md-2 control-label">Complemento:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="complement" value="{{ old('complement') }}">

                                        @if ($errors->has('complement'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('complement') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                                    <label for="name" class="col-md-1 control-label">Cidade:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="city" value="{{ old('city') }}">

                                        @if ($errors->has('city'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('city') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <label for="name" class="col-md-2 control-label">Estado:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="state" value="{{ old('state') }}">

                                        @if ($errors->has('state'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('state') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                                    <label for="name" class="col-md-1 control-label">País:</label>
                                    <div class="col-md-4">
                                        <input id="name" type="text" class="form-control" name="country" value="{{ old('country') }}">

                                        @if ($errors->has('country'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('country') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </fieldset>

                            <div class="form-group">
                                <div class="col-md-offset-1">
                                    <button type="submit" class="btn btn-default">Cadastrar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection