routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('addresses', 'AddressesController');
    Route::resource('establishments', 'EstablishmentsController');
    Route::prefix('establishments/addresses/{address}')->group(function () {
        Route::resource('evaluations', 'EvaluationsController');
    });
    Route::get('/user/evaluations', 'UsersController@evaluations')->name('users.evaluations');
});

app/Http/Controllers/AddressesController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Filters\AddressFilters;
use Illuminate\Http\Request;

class AddressesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(AddressFilters $filters)
    {
        $addresses = Address::filter($filters)->paginate(15);

        return view('addresses.index', ['addresses' => $addresses]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function show(Address $address)
    {
        return view('addresses.show', ['address' => $address]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function edit(Address $address)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Address $address)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function destroy(Address $address)
    {
        //
    }
}

resources/views/addresses/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Minhas Avaliações</div>

                    <div class="panel-body">
                        <div class="form-group">
                            <form method="GET" action="{{ route('addresses.index') }}">
                                <div class="input-group">
                                    <input class="form-control" type="text" name="establishment" placeholder="Pesquise o establecimento" value="{{ request()->input('establishment') }}" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"><span style="margin-left:10px;">Buscar</span></button>
                                    </span>
                                    </span>
                                </div>
                            </form>
                        </div>

                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Estabelecimento</th>
                                    <th>Tipo</th>
                                    <th>Endereço</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            @forelse($addresses as $address)
                                <tr>
                                    <th scope="row">{{ $address->id }}</th>
                                    <td>{{ $address->establishment->name }}</td>
                                    <td>{{ $address->establishment->type->name }}</td>
                                    <td>{{ $address->compressed }}</td>
                                    <td>
                                        @if ($address->evaluations->isNotEmpty())
                                            <a class="btn btn-default"
                                                href="{{ route('addresses.show', $address) }}"
                                                role="button">
                                                Avaliações
                                            </a>
                                        @else
                                            <a class="btn btn-primary"
                                               href="{{ route('evaluations.create', $address) }}"
                                               role="button">
                                                Criar uma Nova Avaliação
                                            </a>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">Nenhum registro cadastrado!</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="panel-footer">
                        {{ $addresses->appends(request()->except('page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/addresses/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h1>{{ $address->establishment->name }}</h1>
                    <h3>{{ $address->street }}, {{ $address->number }} - {{ $address->district }}</h3>
                    <h3>{{ $address->city }} - {{ $address->state }} - {{ $address->country }}</h3>
                    @empty (!$address->complement)
                        <h3>{{ $address->complement }}</h3>
                    @endempty
                    <br>
                    <a class="btn btn-primary" href="{{ route('evaluations.create', $address) }}" role="button">Nova Avaliação</a>
                </div>

                @forelse($address->evaluations as $evaluation)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ $evaluation->user->name }}</h3>
                        </div>
                        <div class="panel-body">
                            <h2>Avaliação Geral: <strong>{{ $evaluation->overall_rating }}</strong></h2>
                            <h2>{!! $evaluation->has_internet ? 'Com Internet' : '<strike>Sem Internet</strike>' !!}</h2>
                        </div>
                        <div class="panel-footer">
                            <a class="btn btn-success btn-sm" href="{{ route('evaluations.show', [$address, $evaluation]) }}" role="button">Vizualizar</a>
                            @can('update-evaluation', $evaluation)
                                <a class="btn btn-warning btn-sm" href="{{ route('evaluations.edit', [$address, $evaluation]) }}" role="button">Alterar</a>
                            @endcan
                        </div>
                    </div>
                @empty
                    <div class="panel panel-default">
                        <div class="panel-body">
                            Nenhuma avaliação encontrada!
                        </div>
                    </div>
                @endforelse
            </div>
        </div>
    </div>
@endsection