routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('addresses', 'AddressesController');
    Route::resource('establishments', 'EstablishmentsController');
    Route::prefix('establishments/addresses/{address}')->group(function () {
        Route::resource('evaluations', 'EvaluationsController');
    });
    Route::get('/user/evaluations', 'UsersController@evaluations')->name('users.evaluations');
});

app/Evaluation.php
<?php
/**
 * Evaluation File
 *
 * PHP version 7
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Evaluation Class
 *
 * @category Model
 * @package  App
 * @author   Victor Hugo <victorhsanjos@gmail.com>
 * @license  https://choosealicense.com/licenses/mit/ MIT License
 * @link     https://bitbucket.org/victorhsanjos/has-wifi/
 */
class Evaluation extends Model
{
    protected $fillable = [
        'address_id',
        'user_id',
        'has_internet',
        'internet_speed',
        'is_open_internet',
        'internet_password',
        'attendance_rating',
        'price_rating',
        'comfort_rating',
        'noise_rating',
        'overall_rating',
    ];

    /**
     * Get Attendance Rating Attribute
     *
     * @return string
     */
    public function getAttendanceRatingSymbolAttribute()
    {
        return str_repeat('&#x263A; ', $this->attendance_rating);
    }

    /**
     * Get PriceRating Symbol Attribute
     *
     * @return string
     */
    public function getPriceRatingSymbolAttribute()
    {
        return str_repeat('$ ', $this->price_rating);
    }

    /**
     * Get Comfort Rating Symbol Attribute
     *
     * @return string
     */
    public function getComfortRatingSymbolAttribute()
    {
        return str_repeat('&#x26F1; ', $this->comfort_rating);
    }

    /**
     * Get Noise Rating Symbol Attribute
     *
     * @return string
     */
    public function getNoiseRatingSymbolAttribute()
    {
        return str_repeat('&#x266C; ', $this->noise_rating);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function address()
    {
        return $this->belongsTo(Address::class);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function foods()
    {
        return $this->belongsToMany(Food::class);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function drinks()
    {
        return $this->belongsToMany(Drink::class);
    }

    /**
     * The relationship
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function accommodations()
    {
        return $this->belongsToMany(Accommodation::class);
    }
}

app/Http/Controllers/EvaluationsController.php
<?php

namespace App\Http\Controllers;

use App\Accommodation;
use App\Address;
use App\Drink;
use App\Evaluation;
use App\Food;
use App\Http\Requests\CreateEvaluationRequest;
use App\Http\Requests\UpdateEvaluationRequest;
use Illuminate\Http\Request;

class EvaluationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Address $address)
    {
        return view('evaluations.create', [
            'address' => $address,
            'foods' => Food::all(),
            'drinks' => Drink::all(),
            'accommodations' => Accommodation::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEvaluationRequest $request, Address $address)
    {
        $evaluation = new Evaluation(array_add($request->all(), 'user_id', $request->user()->id));

        $address->evaluations()->save($evaluation);

        $evaluation = $evaluation->refresh();

        $evaluation->foods()->attach($request->input('foods.*'));
        $evaluation->drinks()->attach($request->input('drinks.*'));
        $evaluation->accommodations()->attach($request->input('accommodations.*'));

        return redirect()->route('addresses.show', $address);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function show(Address $address, Evaluation $evaluation)
    {
        return view('evaluations.show', ['address' => $address, 'evaluation' => $evaluation]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function edit(Address $address, Evaluation $evaluation)
    {
        $this->authorize('update-evaluation', $evaluation);

        return view('evaluations.edit', [
            'address' => $address,
            'evaluation' => $evaluation,
            'foods' => Food::all(),
            'drinks' => Drink::all(),
            'accommodations' => Accommodation::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEvaluationRequest $request, Address $address, Evaluation $evaluation)
    {
        $this->authorize('update-evaluation', $evaluation);

        $evaluation->fill(array_add($request->all(), 'user_id', $request->user()->id));
        $evaluation->save();

        $evaluation->foods()->sync($request->input('foods.*'));
        $evaluation->drinks()->sync($request->input('drinks.*'));
        $evaluation->accommodations()->sync($request->input('accommodations.*'));

        return redirect()->route('evaluations.show', [$address, $evaluation]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Evaluation  $evaluation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Evaluation $evaluation)
    {
        //
    }
}

resources/views/evaluations/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="jumbotron">
                    <h1>{{ $address->establishment->name }}</h1>
                    <h3>{{ $address->street }}, {{ $address->number }} - {{ $address->district }}</h3>
                    <h3>{{ $address->city }} - {{ $address->state }} - {{ $address->country }}</h3>
                    @empty (!$address->complement)
                        <h3>{{ $address->complement }}</h3>
                    @endempty
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2>Avaliação Geral - {{ $evaluation->overall_rating }}</h2>
                        <h3>{{ $evaluation->user->name }}</h3>
                    </div>

                    <div class="panel-body">
                        @if($evaluation->has_internet)
                            <h3>Internet</h3>
                            <p>Velocidade: {{ $evaluation->internet_speed }}</p>
                            @if ($evaluation->is_open_internet)
                                <p>Rede Aberta</p>
                            @else
                                <p>Senha: {{ $evaluation->internet_password }}</p>
                            @endif
                            <hr>
                        @endif

                        @if($evaluation->foods->isNotEmpty())
                            <h3>Comidas</h3>
                            <ul>
                                @foreach($evaluation->foods as $food)
                                    <li>{{ $food->name }}</li>
                                @endforeach
                            </ul>
                            <hr>
                        @endif

                        @if($evaluation->drinks->isNotEmpty())
                            <h3>Bebidas</h3>
                            <ul>
                                @foreach($evaluation->drinks as $drink)
                                    <li>{{ $drink->name }}</li>
                                @endforeach
                            </ul>
                            <hr>
                        @endif

                            <h3>Atendimento</h3>
                            <span title="{{ $evaluation->attendance_rating }}">{{ $evaluation->attendance_rating_symbol }}</span>
                            <hr>

                            <h3>Preço</h3>
                            <span title="{{ $evaluation->price_rating }}">{{ $evaluation->price_rating_symbol }}</span>
                            <hr>

                            <h3>Conforto</h3>
                            <span title="{{ $evaluation->comfort_rating }}">{{ $evaluation->comfort_rating_symbol }}</span>
                            <hr>

                            @if($evaluation->accommodations->isNotEmpty())
                                <h3>Acomodações</h3>
                                <ul>
                                    @foreach($evaluation->accommodations as $accommodation)
                                        <li>{{ $accommodation->name }}</li>
                                    @endforeach
                                </ul>
                                <hr>
                            @endif

                            <h3>Ruído (Barulho)</h3>
                            <span title="{{ $evaluation->noise_rating }}">{{ $evaluation->noise_rating_symbol }}</span>
                            <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection